export default {
  extends: ['@commitlint/config-conventional'],
  rules: {
    'type-enum': [
      2,
      'always',
      [
        'feat',
        'fix',
        'docs',
        'style',
        'refactor',
        'test',
        'chore',
        'perf',
        'ci',
        'revert',
      ],
    ],
    'scope-enum': [
      1,
      'always',
      [
        'admin',
        'marketplace',
        'remarketing',
        'auth',
        'data-room',
        'edge-fn',
        'scoring',
        'db',
        'ui',
        'deps',
        'ci',
        'enrichment',
        'chat',
        'integrations',
        'phoneburner',
        'fireflies',
        'docuseal',
        'smartlead',
        'heyreach',
        'salesforce',
        'analytics',
        'security',
      ],
    ],
    'subject-case': [2, 'never', ['start-case', 'pascal-case', 'upper-case']],
    'header-max-length': [2, 'always', 100],
  },
};
