import { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { subDays } from 'date-fns';
import { supabase } from '@/integrations/supabase/client';
import { useAuth } from '@/contexts/AuthContext';
import {
  useDailyTasks,
  useDeleteTask,
  useApproveTask,
  useApproveAllTasks,
} from '@/hooks/useDailyTasks';
import { useCancelTask } from '@/hooks/useTaskActions';
import { useToast } from '@/hooks/use-toast';
import { useExistingTags } from '@/hooks/useTaskTags';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { ListChecks, Mic, AlertTriangle, Zap, CalendarDays } from 'lucide-react';
import { cn } from '@/lib/utils';
import { AddTaskDialog } from '@/components/daily-tasks/AddTaskDialog';
import { EditTaskDialog } from '@/components/daily-tasks/EditTaskDialog';
import { ReassignDialog } from '@/components/daily-tasks/ReassignDialog';
import { PinDialog } from '@/components/daily-tasks/PinDialog';
import { TaskCalendarView } from '@/components/daily-tasks/TaskCalendarView';
import { TeamWorkloadCard } from '@/components/daily-tasks/TeamWorkloadCard';
import type { DailyStandupTaskWithRelations } from '@/types/daily-tasks';

import {
  DashboardHeader,
  StandupsTabContent,
  TaskStatsCards,
  TaskFiltersBar,
  TaskListContent,
  PendingApprovalSection,
  DeleteTaskDialog,
  useSyncMeetings,
  useTeamMembers,
  useTaskFilters,
} from './daily-task-dashboard';

const GENERATION_SOURCE_LABELS: Record<string, string> = {
  call_disposition: 'Call',
  email_reply: 'Email',
  stage_entry: 'Stage',
  stale_deal: 'Stale',
  recurrence: 'Recurring',
  meeting_extraction: 'Meeting',
  template: 'Template',
};

const GENERATION_SOURCE_COLORS: Record<string, string> = {
  call_disposition: 'bg-emerald-50 text-emerald-700 border-emerald-200',
  email_reply: 'bg-sky-50 text-sky-700 border-sky-200',
  stage_entry: 'bg-indigo-50 text-indigo-700 border-indigo-200',
  stale_deal: 'bg-red-50 text-red-700 border-red-200',
  recurrence: 'bg-blue-50 text-blue-700 border-blue-200',
  meeting_extraction: 'bg-purple-50 text-purple-700 border-purple-200',
  template: 'bg-violet-50 text-violet-700 border-violet-200',
};

const DailyTaskDashboard = () => {
  const { teamRole } = useAuth();
  const { toast } = useToast();
  const isLeadership = teamRole === 'owner' || teamRole === 'admin';

  const [pageTab, setPageTab] = useState<'tasks' | 'standups'>('tasks');
  const [view, setView] = useState<'my' | 'all'>('my');
  const [entityFilter, setEntityFilter] = useState<'all' | 'deal' | 'buyer'>('all');
  const [showCompleted, setShowCompleted] = useState(false);
  const [showAutoGenerated, setShowAutoGenerated] = useState(false);
  const [selectedTags, setSelectedTags] = useState<Set<string>>(new Set());
  const [selectedMeeting, setSelectedMeeting] = useState<string | null>(null);
  const [addDialogOpen, setAddDialogOpen] = useState(false);
  const [editTask, setEditTask] = useState<DailyStandupTaskWithRelations | null>(null);
  const [reassignTask, setReassignTask] = useState<DailyStandupTaskWithRelations | null>(null);
  const [pinTask, setPinTask] = useState<DailyStandupTaskWithRelations | null>(null);
  const [deleteTask, setDeleteTask] = useState<DailyStandupTaskWithRelations | null>(null);
  const [calendarView, setCalendarView] = useState(false);

  const deleteTaskMutation = useDeleteTask();
  const approveTask = useApproveTask();
  const approveAll = useApproveAllTasks();
  const dismissTask = useCancelTask();
  const { data: allDistinctTags } = useExistingTags();
  const syncMeetings = useSyncMeetings();
  const teamMembers = useTeamMembers();

  const {
    data: tasks,
    isLoading,
    error: tasksError,
  } = useDailyTasks({
    view,
    includeCompleted: showCompleted,
  });

  // Stale deals: deals with no activity in 7+ days
  const staleCutoff = subDays(new Date(), 7).toISOString();
  const { data: staleDeals } = useQuery({
    queryKey: ['stale-deals', staleCutoff],
    queryFn: async () => {
      const { data, error } = await (supabase as any)
        .from('deal_pipeline')
        .select('id, title, last_activity_at, deal_stages(name)')
        .lt('last_activity_at', staleCutoff)
        .order('last_activity_at', { ascending: true })
        .limit(10);
      if (error) throw error;
      return data as unknown as Array<{
        id: string;
        title: string | null;
        last_activity_at: string | null;
        deal_stages: { name: string } | null;
      }>;
    },
  });

  // Auto-generated tasks count
  const autoGeneratedTasks = (tasks || []).filter((t) => t.auto_generated || t.generation_source);

  const {
    pendingApprovalTasks,
    approvedTasks,
    todayTasks,
    futureTasks,
    completedTasks,
    snoozedTasks,
    stats,
    pendingApprovalGroups,
    todayGroups,
    futureGroups,
    completedGroups,
    snoozedGroups,
    distinctMeetings,
  } = useTaskFilters({
    tasks,
    entityFilter,
    selectedMeeting,
    selectedTags,
    showCompleted,
  });

  const handleDelete = async () => {
    if (!deleteTask) return;
    try {
      await deleteTaskMutation.mutateAsync(deleteTask.id);
      setDeleteTask(null);
    } catch (err) {
      toast({
        title: 'Failed to delete task',
        description: err instanceof Error ? err.message : 'Unknown error',
        variant: 'destructive',
      });
      setDeleteTask(null);
    }
  };

  const handleApproveTask = async (taskId: string) => {
    try {
      await approveTask.mutateAsync(taskId);
      toast({ title: 'Task approved' });
    } catch (err) {
      toast({
        title: 'Failed to approve task',
        description: err instanceof Error ? err.message : 'Unknown error',
        variant: 'destructive',
      });
    }
  };

  const handleApproveAll = async () => {
    try {
      await approveAll.mutateAsync();
      toast({ title: `${pendingApprovalTasks.length} tasks approved` });
    } catch (err) {
      toast({
        title: 'Failed to approve tasks',
        description: err instanceof Error ? err.message : 'Unknown error',
        variant: 'destructive',
      });
    }
  };

  const handleDismissTask = async (taskId: string) => {
    try {
      await dismissTask.mutateAsync(taskId);
      toast({ title: 'Task dismissed' });
    } catch (err) {
      toast({
        title: 'Failed to dismiss task',
        description: err instanceof Error ? err.message : 'Unknown error',
        variant: 'destructive',
      });
    }
  };

  const taskHandlers = {
    onEdit: setEditTask,
    onReassign: setReassignTask,
    onPin: setPinTask,
    onDelete: setDeleteTask,
  };

  return (
    <div className="px-4 md:px-8 py-6 space-y-5">
      {/* Header */}
      <DashboardHeader
        onSyncMeetings={() => syncMeetings.mutate()}
        isSyncing={syncMeetings.isPending}
        onAddTask={() => setAddDialogOpen(true)}
      />

      {/* Page Tab Toggle: Tasks | Standups */}
      <div className="flex items-center gap-1 rounded-lg border bg-white p-0.5 w-fit">
        <button
          onClick={() => setPageTab('tasks')}
          className={cn(
            'px-4 py-1.5 text-xs font-medium rounded-md transition-colors',
            pageTab === 'tasks'
              ? 'bg-gray-900 text-white'
              : 'text-muted-foreground hover:text-foreground',
          )}
        >
          <ListChecks className="h-3.5 w-3.5 inline mr-1.5 -mt-0.5" />
          Tasks
        </button>
        <button
          onClick={() => setPageTab('standups')}
          className={cn(
            'px-4 py-1.5 text-xs font-medium rounded-md transition-colors',
            pageTab === 'standups'
              ? 'bg-gray-900 text-white'
              : 'text-muted-foreground hover:text-foreground',
          )}
        >
          <Mic className="h-3.5 w-3.5 inline mr-1.5 -mt-0.5" />
          Standups
        </button>
      </div>

      {/* Standups Tab */}
      {pageTab === 'standups' && <StandupsTabContent />}

      {/* Tasks Tab */}
      {pageTab === 'tasks' && (
        <>
          {/* KPI Cards */}
          <TaskStatsCards stats={stats} />

          {/* Team Workload */}
          <TeamWorkloadCard />

          {/* Stale Deals & Auto-Generated row */}
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            {/* Stale Deals Widget */}
            {(staleDeals?.length ?? 0) > 0 && (
              <Card className="border-amber-200">
                <CardHeader className="pb-2 pt-3 px-4">
                  <CardTitle className="text-sm flex items-center gap-1.5">
                    <AlertTriangle className="h-4 w-4 text-amber-600" />
                    Stale Deals
                    <Badge
                      variant="outline"
                      className="ml-auto text-[10px] h-5 bg-amber-50 text-amber-700 border-amber-200"
                    >
                      {staleDeals?.length ?? 0} deals
                    </Badge>
                  </CardTitle>
                </CardHeader>
                <CardContent className="px-4 pb-3">
                  <p className="text-[11px] text-muted-foreground mb-2">No activity in 7+ days</p>
                  <div className="space-y-1.5 max-h-36 overflow-y-auto">
                    {(staleDeals || []).map((deal) => (
                      <div
                        key={deal.id}
                        className="flex items-center justify-between rounded border px-2 py-1.5 text-xs"
                      >
                        <span className="font-medium truncate flex-1">
                          {deal.title || 'Untitled'}
                        </span>
                        {deal.deal_stages?.name && (
                          <Badge variant="outline" className="text-[9px] h-4 px-1 ml-2 shrink-0">
                            {deal.deal_stages.name}
                          </Badge>
                        )}
                        <span className="text-[10px] text-muted-foreground ml-2 shrink-0 tabular-nums">
                          {deal.last_activity_at
                            ? new Date(deal.last_activity_at).toLocaleDateString()
                            : 'Never'}
                        </span>
                      </div>
                    ))}
                  </div>
                </CardContent>
              </Card>
            )}

            {/* Auto-Generated Tasks summary */}
            {autoGeneratedTasks.length > 0 && (
              <Card className="border-violet-200">
                <CardHeader className="pb-2 pt-3 px-4">
                  <CardTitle className="text-sm flex items-center gap-1.5">
                    <Zap className="h-4 w-4 text-violet-600" />
                    Auto-Generated Tasks
                    <Badge
                      variant="outline"
                      className="ml-auto text-[10px] h-5 bg-violet-50 text-violet-700 border-violet-200"
                    >
                      {autoGeneratedTasks.length} tasks
                    </Badge>
                  </CardTitle>
                </CardHeader>
                <CardContent className="px-4 pb-3">
                  <p className="text-[11px] text-muted-foreground mb-2">
                    System-created tasks by source
                  </p>
                  <div className="flex flex-wrap gap-1.5">
                    {Object.entries(
                      autoGeneratedTasks.reduce<Record<string, number>>((acc, t) => {
                        const src = t.generation_source || 'system';
                        acc[src] = (acc[src] || 0) + 1;
                        return acc;
                      }, {}),
                    ).map(([source, count]) => (
                      <Badge
                        key={source}
                        variant="outline"
                        className={cn(
                          'text-[10px] h-5',
                          GENERATION_SOURCE_COLORS[source] ??
                            'bg-gray-50 text-gray-700 border-gray-200',
                        )}
                      >
                        {GENERATION_SOURCE_LABELS[source] ?? source}: {count}
                      </Badge>
                    ))}
                  </div>
                  <button
                    onClick={() => setShowAutoGenerated(!showAutoGenerated)}
                    className="mt-2 text-[11px] text-violet-600 hover:text-violet-800 font-medium"
                  >
                    {showAutoGenerated ? 'Show all tasks' : 'Filter to auto-generated only'}
                  </button>
                </CardContent>
              </Card>
            )}
          </div>

          {/* Pending Approval Banner (leadership only) */}
          <PendingApprovalSection
            pendingApprovalTasks={pendingApprovalTasks}
            pendingApprovalGroups={pendingApprovalGroups}
            approvedTasksCount={approvedTasks.length}
            isLeadership={isLeadership}
            isApprovingAll={approveAll.isPending}
            onApproveAll={handleApproveAll}
            onApproveTask={handleApproveTask}
            onDismissTask={handleDismissTask}
            taskHandlers={taskHandlers}
          />

          {/* View Toggle & Filters */}
          <TaskFiltersBar
            view={view}
            onViewChange={setView}
            entityFilter={entityFilter}
            onEntityFilterChange={setEntityFilter}
            selectedTags={selectedTags}
            onSelectedTagsChange={setSelectedTags}
            allDistinctTags={allDistinctTags}
            selectedMeeting={selectedMeeting}
            onSelectedMeetingChange={setSelectedMeeting}
            distinctMeetings={distinctMeetings}
            showCompleted={showCompleted}
            onShowCompletedChange={setShowCompleted}
          />

          {/* Calendar / List Toggle */}
          <div className="flex items-center gap-1 rounded-lg border bg-white p-0.5 w-fit">
            <button
              onClick={() => setCalendarView(false)}
              className={cn(
                'px-3 py-1 text-xs font-medium rounded-md transition-colors',
                !calendarView
                  ? 'bg-gray-900 text-white'
                  : 'text-muted-foreground hover:text-foreground',
              )}
            >
              <ListChecks className="h-3.5 w-3.5 inline mr-1 -mt-0.5" />
              List
            </button>
            <button
              onClick={() => setCalendarView(true)}
              className={cn(
                'px-3 py-1 text-xs font-medium rounded-md transition-colors',
                calendarView
                  ? 'bg-gray-900 text-white'
                  : 'text-muted-foreground hover:text-foreground',
              )}
            >
              <CalendarDays className="h-3.5 w-3.5 inline mr-1 -mt-0.5" />
              Calendar
            </button>
          </div>

          {/* Calendar View */}
          {calendarView && <TaskCalendarView tasks={tasks ?? []} />}

          {/* Task List */}
          {!calendarView && (
            <TaskListContent
              isLoading={isLoading}
              tasksError={tasksError}
              tasks={tasks}
              approvedTasks={approvedTasks}
              pendingApprovalTasks={pendingApprovalTasks}
              todayTasks={todayTasks}
              futureTasks={futureTasks}
              completedTasks={completedTasks}
              snoozedTasks={snoozedTasks}
              todayGroups={todayGroups}
              futureGroups={futureGroups}
              completedGroups={completedGroups}
              snoozedGroups={snoozedGroups}
              showCompleted={showCompleted}
              view={view}
              isLeadership={isLeadership}
              taskHandlers={taskHandlers}
              onViewChange={setView}
              onAddTask={() => setAddDialogOpen(true)}
            />
          )}
        </>
      )}

      {/* Dialogs */}
      <AddTaskDialog
        open={addDialogOpen}
        onOpenChange={setAddDialogOpen}
        teamMembers={teamMembers}
      />
      <EditTaskDialog
        task={editTask}
        open={!!editTask}
        onOpenChange={(open) => !open && setEditTask(null)}
      />
      <ReassignDialog
        task={reassignTask}
        open={!!reassignTask}
        onOpenChange={(open) => !open && setReassignTask(null)}
        teamMembers={teamMembers}
      />
      <PinDialog
        task={pinTask}
        open={!!pinTask}
        onOpenChange={(open) => !open && setPinTask(null)}
      />
      <DeleteTaskDialog
        task={deleteTask}
        onOpenChange={() => setDeleteTask(null)}
        onConfirm={handleDelete}
      />
    </div>
  );
};

export default DailyTaskDashboard;
