
INSERT INTO connection_requests (listing_id, source, status, lead_name, lead_email, lead_phone, lead_company, lead_role, user_message, user_id, source_metadata, created_at)
VALUES
  ('a6e20eba-768b-43bb-97ea-ddb6e679fe73', 'webflow', 'pending', 'Joshua Klieger', 'jklieger@rydalsp.com', '9735256701', 'Rydal Service Partners', 'corporate', '"We have an existing plumbing business in the northeast that would be highly synergistic, and $25M of dry powder to pursue add-ons."', NULL, '{"import_method": "csv_backfill", "ip_address": "4.28.184.238", "page_url": "/off-market-deal-memos/municipal-meter-installation-services"}'::jsonb, '2026-04-08T15:56:59Z'),

  ('a6e20eba-768b-43bb-97ea-ddb6e679fe73', 'webflow', 'pending', 'Jack Harvey', 'jack@durationgroup.com', '9175950226', 'Duration Group', 'corporate', E'"Holding company with $30m of permanent, committed equity to buying and building critical services businesses over the long term."\n\n--- Second submission (3:34 PM) ---\n"Duration Group is a holding company with $30m of permanent, committed equity capital focused on buying and building critical service businesses over the long term."', NULL, '{"import_method": "csv_backfill", "ip_address": "76.216.4.60", "page_url": "/off-market-deal-memos/municipal-meter-installation-services", "note": "Two form submissions merged (2:48 PM and 3:34 PM)"}'::jsonb, '2026-04-08T14:48:41Z'),

  ('a6e20eba-768b-43bb-97ea-ddb6e679fe73', 'webflow', 'pending', 'Kyle Tamboli', 'kyle.tamboli@anconaholdings.com', '2623646906', 'Ancona Holdings', 'independent_sponsor', '"We are backed by long-term holdco capital providers and are focused primarily on the water treatment market. This opportunity looks to fit our criteria. Our preference is for management and/or founders to remain with the business post-closing, while we provide resources to grow both organically and through acquisitions."', '9562e5ba-2a86-438d-b183-d8c8a054c7fe', '{"import_method": "csv_backfill", "ip_address": "140.248.30.1", "page_url": "/off-market-deal-memos/municipal-meter-installation-services"}'::jsonb, '2026-04-08T14:59:23Z'),

  ('a6e20eba-768b-43bb-97ea-ddb6e679fe73', 'webflow', 'pending', 'Jen Fair', 'jen@nbeachholdings.com', '3304644837', 'North Beach Holdings', 'independent_sponsor', '"High recurring revenue, essential services, low or no cyclicality"', '36217e0a-00bb-4042-8dce-be289bb308b7', '{"import_method": "csv_backfill", "ip_address": "65.25.47.107", "page_url": "/off-market-deal-memos/municipal-meter-installation-services"}'::jsonb, '2026-04-08T14:56:21Z'),

  ('a6e20eba-768b-43bb-97ea-ddb6e679fe73', 'webflow', 'pending', 'Thomas Woldemariam', 'thomas@contactlandmark.com', '5717333662', 'contactlandmark.com', 'family_office', '"We have a very high level of interest in this opportunity, and view it as highly aligned with our focus on home & commercial facility services. We are a family-office backed platform with committed capital that comes 100% from wealthy families & high net worth individuals with a strong track record of building $100 million+ companies in the industry. Our committed capital and familiarity with the industry allows us to move quickly and be thoughtful through diligence."', NULL, '{"import_method": "csv_backfill", "ip_address": "172.56.27.91", "page_url": "/off-market-deal-memos/municipal-meter-installation-services"}'::jsonb, '2026-04-08T14:44:50Z'),

  ('d136656a-433e-47fe-8813-f711eedfddab', 'webflow', 'pending', 'Brendan Doney', 'brendan@willowbrookcp.com', '16265343700', 'www.willowbrookcp.com', 'individual_buyer', '"Hey guys. I am an investor backed acquisition entrepreneur based in LA willing to relocate for the right opportunity. I have looked at a number of restoration deals and really like the space. I am typically looking for essential local service opportunities in the $700k-$2M EBTIDA range. I plan to step into CEO role long term. I also have a personal connection to this space after toxic mold exposure in 2018 and a 4+ year recovery. Thanks. Brendan"', '63b49360-3359-4df2-bb99-dc865a164aed', '{"import_method": "csv_backfill", "ip_address": "68.118.145.241", "page_url": "/off-market-deal-memos/florida-property-damage-restoration-emergency-services"}'::jsonb, '2026-04-08T15:20:38Z');
