CREATE OR REPLACE VIEW public.marketplace_listings AS
SELECT ml.id,
    ml.title,
    ml.description,
    ml.description_html,
    ml.description_json,
    ml.hero_description,
    COALESCE(deal.category, ml.category) AS category,
    COALESCE(deal.categories, ml.categories) AS categories,
    COALESCE(deal.address_state, deal.location, ml.location) AS location,
    COALESCE(NULLIF(deal.revenue, 0), NULLIF(ml.revenue, 0)) AS revenue,
    COALESCE(NULLIF(deal.ebitda, 0), NULLIF(ml.ebitda, 0)) AS ebitda,
    COALESCE(NULLIF(deal.full_time_employees, 0), NULLIF(ml.full_time_employees, 0)) AS full_time_employees,
    ml.image_url,
    ml.status,
    ml.status_tag,
    ml.tags,
    ml.created_at,
    ml.updated_at,
    ml.published_at,
    ml.is_internal_deal,
    ml.deleted_at,
    ml.visible_to_buyer_types,
    ml.acquisition_type,
    ml.part_time_employees,
    ml.custom_metric_label,
    ml.custom_metric_value,
    ml.custom_metric_subtitle,
    ml.metric_3_type,
    ml.metric_3_custom_label,
    ml.metric_3_custom_value,
    ml.metric_3_custom_subtitle,
    ml.metric_4_type,
    ml.metric_4_custom_label,
    ml.metric_4_custom_value,
    ml.metric_4_custom_subtitle,
    ml.revenue_metric_subtitle,
    ml.ebitda_metric_subtitle,
    ml.custom_sections,
    ml.source_deal_id
   FROM listings ml
     LEFT JOIN listings deal ON ml.source_deal_id = deal.id
  WHERE ml.status = 'active'::text AND ml.deleted_at IS NULL AND ml.is_internal_deal = false;