-- Seed a new GP Partners listing record
INSERT INTO public.listings (
  title,
  internal_company_name,
  website,
  main_contact_name,
  main_contact_title,
  main_contact_email,
  main_contact_phone,
  industry,
  category,
  location,
  address_city,
  address_state,
  revenue,
  ebitda,
  description,
  deal_source,
  is_internal_deal
) VALUES (
  'TEST - Sample HVAC Services Company',
  'TEST Sample HVAC Co.',
  'www.test-sample-hvac.com',
  'Test Contact Smith',
  'Owner / CEO',
  'test@sample-hvac-test.com',
  '(312) 586-9748',
  'HVAC',
  'Home Services',
  'Chicago, IL',
  'Chicago',
  'IL',
  3500000,
  750000,
  'TEST ROW - Sample HVAC services company for dialer testing. This is not a real company. All data is test/sample data.',
  'gp_partner',
  true
)