
INSERT INTO connection_requests (
  id, listing_id, status, source, source_metadata,
  lead_email, lead_name, lead_company, lead_role,
  lead_agreement_email_status, lead_agreement_email_sent_at,
  lead_nda_signed, lead_nda_signed_at,
  lead_fee_agreement_signed, lead_fee_agreement_signed_at,
  user_message, created_at
) VALUES
(gen_random_uuid(), (SELECT id FROM listings ORDER BY created_at DESC LIMIT 1), 'pending', 'webflow',
  '{"form_name":"Deal Request Form","test_case":"1_email_sent_normal","test_v2":true}'::jsonb,
  'test-v2-case1@emailsent-capital.com', 'Case 1: Email Sent (Normal)', 'EmailSent Capital Partners', 'Managing Director',
  'sent', now() - interval '3 hours', false, NULL, false, NULL,
  'Interested in learning more about this opportunity.', now() - interval '3 hours'),
(gen_random_uuid(), (SELECT id FROM listings ORDER BY created_at DESC LIMIT 1), 'pending', 'webflow',
  '{"form_name":"Deal Request Form","test_case":"2_already_covered","test_v2":true}'::jsonb,
  'test-v2-case2@coveredfirm-llc.com', 'Case 2: Already Covered', 'CoveredFirm LLC', 'Partner',
  'already_covered', NULL, true, now() - interval '30 days', true, now() - interval '25 days',
  'We would like to review the materials.', now() - interval '2 hours'),
(gen_random_uuid(), (SELECT id FROM listings ORDER BY created_at DESC LIMIT 1), 'pending', 'webflow',
  '{"form_name":"Deal Request Form","test_case":"3_awaiting_send","test_v2":true}'::jsonb,
  'test-v2-case3@awaitingsend-corp.com', 'Case 3: Awaiting Send', 'AwaitingSend Corp', 'VP Corp Dev',
  NULL, NULL, false, NULL, false, NULL,
  'Please send us the NDA and fee agreement.', now() - interval '1 hour'),
(gen_random_uuid(), (SELECT id FROM listings ORDER BY created_at DESC LIMIT 1), 'pending', 'webflow',
  '{"form_name":"Deal Request Form","test_case":"4_duplicate_skipped","is_duplicate":true,"test_v2":true}'::jsonb,
  'test-v2-case4@duplicate-inc.com', 'Case 4: Duplicate Skipped', 'Duplicate Submissions Inc', 'Analyst',
  'duplicate_skipped', NULL, false, NULL, false, NULL,
  'Submitting again just in case.', now() - interval '45 minutes'),
(gen_random_uuid(), (SELECT id FROM listings ORDER BY created_at DESC LIMIT 1), 'pending', 'webflow',
  '{"form_name":"Deal Request Form","test_case":"5_partial_nda_signed","test_v2":true}'::jsonb,
  'test-v2-case5@partial-nda.com', 'Case 5: Partial (NDA ✓, Fee ✗)', 'PartialNDA Holdings', 'Director',
  'sent', now() - interval '2 hours', true, now() - interval '60 days', false, NULL,
  'Looking to explore this investment opportunity.', now() - interval '2 hours'),
(gen_random_uuid(), (SELECT id FROM listings ORDER BY created_at DESC LIMIT 1), 'pending', 'webflow',
  '{"form_name":"Deal Request Form","test_case":"6_partial_fee_signed","test_v2":true}'::jsonb,
  'test-v2-case6@partial-fee.com', 'Case 6: Partial (Fee ✓, NDA ✗)', 'PartialFee Advisors', 'Principal',
  'sent', now() - interval '90 minutes', false, NULL, true, now() - interval '45 days',
  'Interested in the teaser materials.', now() - interval '90 minutes'),
(gen_random_uuid(), (SELECT id FROM listings ORDER BY created_at DESC LIMIT 1), 'pending', 'webflow',
  '{"form_name":"Deal Request Form","test_case":"7_pending_marketplace_user","test_v2":true}'::jsonb,
  'test-v2-case7@pending-marketplace.com', 'Case 7: Pending Marketplace User', 'PendingMarketplace Group', 'Associate',
  'sent', now() - interval '1 hour', false, NULL, false, NULL,
  'Also signed up on marketplace, waiting for approval.', now() - interval '1 hour'),
(gen_random_uuid(), (SELECT id FROM listings ORDER BY created_at DESC LIMIT 1), 'pending', 'webflow',
  '{"form_name":"Deal Request Form","test_case":"8_approved_marketplace_covered","test_v2":true}'::jsonb,
  'test-v2-case8@approved-covered.com', 'Case 8: Approved Marketplace + Covered', 'ApprovedCovered PE', 'Managing Partner',
  'already_covered', NULL, true, now() - interval '90 days', true, now() - interval '85 days',
  'Already have agreements on file through marketplace.', now() - interval '30 minutes'),
(gen_random_uuid(), (SELECT id FROM listings ORDER BY created_at DESC LIMIT 1), 'pending', 'webflow',
  '{"form_name":"Deal Request Form","test_case":"9_no_firm_resolved","test_v2":true}'::jsonb,
  'test-v2-case9@unknowndomain-xyz.com', 'Case 9: No Firm Resolved', 'Unknown Domain XYZ', 'Founder',
  NULL, NULL, false, NULL, false, NULL,
  'First time hearing about this platform.', now() - interval '15 minutes'),
(gen_random_uuid(), (SELECT id FROM listings ORDER BY created_at DESC LIMIT 1), 'pending', 'webflow',
  '{"form_name":"Deal Request Form","test_case":"10_failed_delivery","test_v2":true}'::jsonb,
  'test-v2-case10@bounced-email.invalid', 'Case 10: Failed Delivery', 'BouncedEmail Corp', 'CFO',
  'failed', now() - interval '2 hours', false, NULL, false, NULL,
  'Please send me the documents.', now() - interval '2 hours');
