-- Fix existing listings with full state names in address_state
UPDATE listings SET address_state = 'AL' WHERE address_state = 'Alabama';
UPDATE listings SET address_state = 'AK' WHERE address_state = 'Alaska';
UPDATE listings SET address_state = 'AZ' WHERE address_state = 'Arizona';
UPDATE listings SET address_state = 'AR' WHERE address_state = 'Arkansas';
UPDATE listings SET address_state = 'CA' WHERE address_state = 'California';
UPDATE listings SET address_state = 'CO' WHERE address_state = 'Colorado';
UPDATE listings SET address_state = 'CT' WHERE address_state = 'Connecticut';
UPDATE listings SET address_state = 'DE' WHERE address_state = 'Delaware';
UPDATE listings SET address_state = 'FL' WHERE address_state = 'Florida';
UPDATE listings SET address_state = 'GA' WHERE address_state = 'Georgia';
UPDATE listings SET address_state = 'HI' WHERE address_state = 'Hawaii';
UPDATE listings SET address_state = 'ID' WHERE address_state = 'Idaho';
UPDATE listings SET address_state = 'IL' WHERE address_state = 'Illinois';
UPDATE listings SET address_state = 'IN' WHERE address_state = 'Indiana';
UPDATE listings SET address_state = 'IA' WHERE address_state = 'Iowa';
UPDATE listings SET address_state = 'KS' WHERE address_state = 'Kansas';
UPDATE listings SET address_state = 'KY' WHERE address_state = 'Kentucky';
UPDATE listings SET address_state = 'LA' WHERE address_state = 'Louisiana';
UPDATE listings SET address_state = 'ME' WHERE address_state = 'Maine';
UPDATE listings SET address_state = 'MD' WHERE address_state = 'Maryland';
UPDATE listings SET address_state = 'MA' WHERE address_state = 'Massachusetts';
UPDATE listings SET address_state = 'MI' WHERE address_state = 'Michigan';
UPDATE listings SET address_state = 'MN' WHERE address_state = 'Minnesota';
UPDATE listings SET address_state = 'MS' WHERE address_state = 'Mississippi';
UPDATE listings SET address_state = 'MO' WHERE address_state = 'Missouri';
UPDATE listings SET address_state = 'MT' WHERE address_state = 'Montana';
UPDATE listings SET address_state = 'NE' WHERE address_state = 'Nebraska';
UPDATE listings SET address_state = 'NV' WHERE address_state = 'Nevada';
UPDATE listings SET address_state = 'NH' WHERE address_state = 'New Hampshire';
UPDATE listings SET address_state = 'NJ' WHERE address_state = 'New Jersey';
UPDATE listings SET address_state = 'NM' WHERE address_state = 'New Mexico';
UPDATE listings SET address_state = 'NY' WHERE address_state = 'New York';
UPDATE listings SET address_state = 'NC' WHERE address_state = 'North Carolina';
UPDATE listings SET address_state = 'ND' WHERE address_state = 'North Dakota';
UPDATE listings SET address_state = 'OH' WHERE address_state = 'Ohio';
UPDATE listings SET address_state = 'OK' WHERE address_state = 'Oklahoma';
UPDATE listings SET address_state = 'OR' WHERE address_state = 'Oregon';
UPDATE listings SET address_state = 'PA' WHERE address_state = 'Pennsylvania';
UPDATE listings SET address_state = 'RI' WHERE address_state = 'Rhode Island';
UPDATE listings SET address_state = 'SC' WHERE address_state = 'South Carolina';
UPDATE listings SET address_state = 'SD' WHERE address_state = 'South Dakota';
UPDATE listings SET address_state = 'TN' WHERE address_state = 'Tennessee';
UPDATE listings SET address_state = 'TX' WHERE address_state = 'Texas';
UPDATE listings SET address_state = 'UT' WHERE address_state = 'Utah';
UPDATE listings SET address_state = 'VT' WHERE address_state = 'Vermont';
UPDATE listings SET address_state = 'VA' WHERE address_state = 'Virginia';
UPDATE listings SET address_state = 'WA' WHERE address_state = 'Washington';
UPDATE listings SET address_state = 'WV' WHERE address_state = 'West Virginia';
UPDATE listings SET address_state = 'WI' WHERE address_state = 'Wisconsin';
UPDATE listings SET address_state = 'WY' WHERE address_state = 'Wyoming';
UPDATE listings SET address_state = 'DC' WHERE address_state = 'District of Columbia';

-- Also fix remarketing_buyers with full state names in hq_state
UPDATE remarketing_buyers SET hq_state = 'AL' WHERE hq_state = 'Alabama';
UPDATE remarketing_buyers SET hq_state = 'AK' WHERE hq_state = 'Alaska';
UPDATE remarketing_buyers SET hq_state = 'AZ' WHERE hq_state = 'Arizona';
UPDATE remarketing_buyers SET hq_state = 'AR' WHERE hq_state = 'Arkansas';
UPDATE remarketing_buyers SET hq_state = 'CA' WHERE hq_state = 'California';
UPDATE remarketing_buyers SET hq_state = 'CO' WHERE hq_state = 'Colorado';
UPDATE remarketing_buyers SET hq_state = 'CT' WHERE hq_state = 'Connecticut';
UPDATE remarketing_buyers SET hq_state = 'DE' WHERE hq_state = 'Delaware';
UPDATE remarketing_buyers SET hq_state = 'FL' WHERE hq_state = 'Florida';
UPDATE remarketing_buyers SET hq_state = 'GA' WHERE hq_state = 'Georgia';
UPDATE remarketing_buyers SET hq_state = 'HI' WHERE hq_state = 'Hawaii';
UPDATE remarketing_buyers SET hq_state = 'ID' WHERE hq_state = 'Idaho';
UPDATE remarketing_buyers SET hq_state = 'IL' WHERE hq_state = 'Illinois';
UPDATE remarketing_buyers SET hq_state = 'IN' WHERE hq_state = 'Indiana';
UPDATE remarketing_buyers SET hq_state = 'IA' WHERE hq_state = 'Iowa';
UPDATE remarketing_buyers SET hq_state = 'KS' WHERE hq_state = 'Kansas';
UPDATE remarketing_buyers SET hq_state = 'KY' WHERE hq_state = 'Kentucky';
UPDATE remarketing_buyers SET hq_state = 'LA' WHERE hq_state = 'Louisiana';
UPDATE remarketing_buyers SET hq_state = 'ME' WHERE hq_state = 'Maine';
UPDATE remarketing_buyers SET hq_state = 'MD' WHERE hq_state = 'Maryland';
UPDATE remarketing_buyers SET hq_state = 'MA' WHERE hq_state = 'Massachusetts';
UPDATE remarketing_buyers SET hq_state = 'MI' WHERE hq_state = 'Michigan';
UPDATE remarketing_buyers SET hq_state = 'MN' WHERE hq_state = 'Minnesota';
UPDATE remarketing_buyers SET hq_state = 'MS' WHERE hq_state = 'Mississippi';
UPDATE remarketing_buyers SET hq_state = 'MO' WHERE hq_state = 'Missouri';
UPDATE remarketing_buyers SET hq_state = 'MT' WHERE hq_state = 'Montana';
UPDATE remarketing_buyers SET hq_state = 'NE' WHERE hq_state = 'Nebraska';
UPDATE remarketing_buyers SET hq_state = 'NV' WHERE hq_state = 'Nevada';
UPDATE remarketing_buyers SET hq_state = 'NH' WHERE hq_state = 'New Hampshire';
UPDATE remarketing_buyers SET hq_state = 'NJ' WHERE hq_state = 'New Jersey';
UPDATE remarketing_buyers SET hq_state = 'NM' WHERE hq_state = 'New Mexico';
UPDATE remarketing_buyers SET hq_state = 'NY' WHERE hq_state = 'New York';
UPDATE remarketing_buyers SET hq_state = 'NC' WHERE hq_state = 'North Carolina';
UPDATE remarketing_buyers SET hq_state = 'ND' WHERE hq_state = 'North Dakota';
UPDATE remarketing_buyers SET hq_state = 'OH' WHERE hq_state = 'Ohio';
UPDATE remarketing_buyers SET hq_state = 'OK' WHERE hq_state = 'Oklahoma';
UPDATE remarketing_buyers SET hq_state = 'OR' WHERE hq_state = 'Oregon';
UPDATE remarketing_buyers SET hq_state = 'PA' WHERE hq_state = 'Pennsylvania';
UPDATE remarketing_buyers SET hq_state = 'RI' WHERE hq_state = 'Rhode Island';
UPDATE remarketing_buyers SET hq_state = 'SC' WHERE hq_state = 'South Carolina';
UPDATE remarketing_buyers SET hq_state = 'SD' WHERE hq_state = 'South Dakota';
UPDATE remarketing_buyers SET hq_state = 'TN' WHERE hq_state = 'Tennessee';
UPDATE remarketing_buyers SET hq_state = 'TX' WHERE hq_state = 'Texas';
UPDATE remarketing_buyers SET hq_state = 'UT' WHERE hq_state = 'Utah';
UPDATE remarketing_buyers SET hq_state = 'VT' WHERE hq_state = 'Vermont';
UPDATE remarketing_buyers SET hq_state = 'VA' WHERE hq_state = 'Virginia';
UPDATE remarketing_buyers SET hq_state = 'WA' WHERE hq_state = 'Washington';
UPDATE remarketing_buyers SET hq_state = 'WV' WHERE hq_state = 'West Virginia';
UPDATE remarketing_buyers SET hq_state = 'WI' WHERE hq_state = 'Wisconsin';
UPDATE remarketing_buyers SET hq_state = 'WY' WHERE hq_state = 'Wyoming';
UPDATE remarketing_buyers SET hq_state = 'DC' WHERE hq_state = 'District of Columbia';