import { useMutation, useQueryClient } from '@tanstack/react-query';
import { invokeEdgeFunction } from '@/lib/invoke-edge-function';

export interface SeedBuyerResult {
  buyer_id: string;
  company_name: string;
  action: 'inserted' | 'enriched_existing' | 'probable_duplicate' | 'cached';
  why_relevant: string;
  was_new_record: boolean;
}

export interface SeedBuyersResponse {
  seeded_buyers: SeedBuyerResult[];
  total: number;
  inserted?: number;
  enriched_existing?: number;
  probable_duplicates?: number;
  cached: boolean;
  seeded_at: string;
  cache_key: string;
  model?: string;
  usage?: Record<string, unknown>;
  /** The buyer profile generated by Pass 1 (for debugging/transparency) */
  buyer_profile?: Record<string, unknown>;
}

interface SeedBuyersParams {
  listingId: string;
  maxBuyers?: number;
  forceRefresh?: boolean;
  buyerCategory?: 'sponsors' | 'operating_companies';
  /** Optional job ID for progress tracking */
  jobId?: string;
}

/** Validate edge function response shape to prevent cache corruption */
function validateSeedResult(data: unknown): SeedBuyersResponse {
  const d = data as SeedBuyersResponse;
  if (!d || !Array.isArray(d.seeded_buyers) || typeof d.total !== 'number') {
    throw new Error('Unexpected response shape from seed-buyers');
  }
  return d;
}

export function useSeedBuyers() {
  const queryClient = useQueryClient();

  return useMutation<SeedBuyersResponse, Error, SeedBuyersParams>({
    mutationFn: async ({ listingId, maxBuyers, forceRefresh, buyerCategory, jobId }) => {
      const data = await invokeEdgeFunction<SeedBuyersResponse>('seed-buyers', {
        body: { listingId, maxBuyers, forceRefresh, buyerCategory, jobId },
        // AI search can take a while — allow up to 2 minutes per attempt
        timeoutMs: 120_000,
        maxRetries: 2,
      });
      return validateSeedResult(data);
    },
    onSuccess: (_data, variables) => {
      // Invalidate recommended buyers so the list refreshes with newly seeded buyers
      queryClient.invalidateQueries({
        queryKey: ['new-recommended-buyers', variables.listingId],
      });
    },
  });
}
